#!/bin/bash
# By: that4chanwolf
# Compared to the clusterfuck of if statements that we were using, I think this will work pretty fine.

distro=$(lsb_release -i | sed -e 's/Distributor ID://' -e 's/\t//g')
opersyst=$(uname -o)
kerver=$(uname -r | sed -e 's/.amd64$//' -e 's/.i386$//' -e 's/.i486$//' -e 's/.i686$//' -e 's/.mips$//' -e 's/.sparc$//' -e 's/.generic$//')

echo "$(echo ${distro} | sed -e 's/\t//g') $(echo ${opersyst} | sed -e 's/\t//g') $(echo ${kerver} | sed -e 's/\t//g') "
