#!/bin/bash
# A simple MPD script that shows info on what song is playing
# By: that4chanwolf

# Set the variables for our MPD_HOST and MPD_PORT
MPD_HOST="127.0.0.1"
MPD_PORT="9900"

# Check if MPD is running or not
if [ "$(ps aux | grep mpd | grep root | awk '{ print $11 }')" = '/usr/bin/mpd' ]; then
	# Yes, I am aware that I derped.
	echo "$(mpc -h ${MPD_HOST} -p ${MPD_PORT} current)"
else
	echo 'ERROR: MPD not running!'
fi

